# Generated by Django 5.0.4 on 2024-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0002_taskdeadlineupdate_impact_on_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revised_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
