# Generated by Django 5.0.4 on 2024-05-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0002_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='notes',
        ),
    ]
