# Generated by Django 5.0.4 on 2024-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='project_life_stage',
            field=models.CharField(blank=True, choices=[('Starting', 'Starting'), ('Organize and Prepare', 'Organize and Prepare'), ('Execution', 'Execution'), ('Ending', 'Ending'), ('Closed', 'Closed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allprojects',
            name='project_status',
            field=models.CharField(blank=True, choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=20, null=True),
        ),
    ]
