# Generated by Django 5.0.4 on 2024-07-25 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0004_allprojects_project_life_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'pdf', 'doc', 'docx'])]),
        ),
    ]
