# Generated by Django 5.0.4 on 2024-07-26 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0005_allprojects_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'pdf', 'doc', 'docx'])]),
        ),
    ]
