# Generated by Django 5.0.4 on 2024-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0006_task_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_task_file',
            field=models.FileField(blank=True, null=True, upload_to='user_task_files/'),
        ),
    ]
