# Generated by Django 5.0.4 on 2024-05-27 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTM', '0007_taskdeadlineupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdeadlineupdate',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
